// USER INPUT DETAILS
export const SET_USER_INPUT_DETAILS = 'SET_USER_INPUT_DETAILS';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';
export const ADD_POINTS_TO_USER = 'ADD_POINTS_TO_USER';
export const SET_PLAYER_GAMING_ORDER = 'SET_PLAYER_GAMING_ORDER';
